several Sequence Diagrams
OrganizeIT-FHCW/OrganizeIT pull request #44
Opened 2023-12-03 18:31 UTC by arikkof

some drafts of sequence diagrams #40

2023-12-04 14:48 UTC, michael-mezgo requested changes
Siehe Kommentare 

Sollten wir evtl auch ein größeres Diagramm machen? Aber passt bis auf die eine Anmerkung 😄

2023-12-04 14:48 UTC, michael-mezgo commented on docs/raw-docs/SequenceDiagrams.mdj
StarUML?

2023-12-04 14:48 UTC, michael-mezgo commented on docs/hld-pics/HLD-Sequence-Diagram-Register.png
Ist "Default Space" nicht eher eine neue Lifeline / ein neues Objekt?

2023-12-05 08:43 UTC, arikkof commented on docs/raw-docs/SequenceDiagrams.mdj
habe mich von dir inspirieren lassen

2023-12-05 08:49 UTC, arikkof commented on docs/hld-pics/HLD-Sequence-Diagram-Register.png
ja das stimmt wohl, ich dachte nur, dass die Methode um einen default Space zu erstellen, wohl im Konstruktor der UserAccount Klasse aufgerufen werden sollte, deshalb hab ich es dorthin geschrieben...

2023-12-05 09:37 UTC, michael-mezgo commented on docs/raw-docs/SequenceDiagrams.mdj
> habe mich von dir inspirieren lassen

Perfekt :)

2023-12-10 11:48 UTC, michael-mezgo approved these changes

2023-12-10 11:48 UTC, michael-mezgo commented on docs/hld-pics/HLD-Sequence-Diagram-Register.png
Danke

2023-12-10 11:48 UTC, michael-mezgo commented
@Nour-hash @matschl12 pls review

2023-12-10 19:32 UTC, Nour-hash approved these changes

2023-12-10 19:32 UTC, merged

2023-12-10 21:37 UTC, michael-mezgo commented
@Nour-hash am besten lass immer den Assignee mergen, falls doch noch was geändert gehört - bzw. später falls Konflikt auftreten, kann auch dieser das am besten lösen.
Nach dem Mergen kann der Branch auch gelöscht werden.