activity diagram
OrganizeIT-FHCW/OrganizeIT pull request #46
Opened 2023-12-05 16:40 UTC by Nour-hash

#45

2023-12-06 08:40 UTC, arikkof reviewed
- file should not be in root directory

2023-12-06 08:41 UTC, arikkof commented
- as far as i know one activity diagram should consist of one activity only...

2023-12-06 08:43 UTC, arikkof commented
- the diamond-shaped decision nodes should not have text in them

2023-12-06 08:44 UTC, arikkof commented
- swim lanes should be used to differentiate between the activities of different entities

2023-12-06 08:57 UTC, michael-mezgo requested changes
- [ ] Auf alle fälle: Files verschieben
- [x] Über Vorschläge reden

2023-12-06 09:02 UTC, michael-mezgo commented
@Nour-hash falscher Branch! - falsche Zuordnung (du hast Issue #39) (#45 ist allgemein)

2023-12-06 23:29 UTC, michael-mezgo commented
> wie verschiebe ich die alten Datein in ein ordner

Zumindest unter Unix (unter Windows sollte es auch die GitShell geben): git mv diagram.png docs/hld-pics/diagram.png

und das andere bitte unter docs/raw-documents/

Wenns leichter ist kannst du auch den Main in deinen Branch rein mergen. Dann hast du auch die directories. 

@Nour-hash

2023-12-06 23:34 UTC, michael-mezgo requested changes
Sync Data evtl auch zu Beginn? 
Bei den Swim Lanes hat der Server auch was mit Sync-Data zu tun fällt mir grad auf. 

Sollten über das Morgen nochmals reden. 

Ansonsten passts gut.

Bitte verschieben die Dateien -> daher habe ich noch Änderungen angefordert

2023-12-06 23:34 UTC, michael-mezgo commented on Organize_it_activity_diagram-Seite-1.drawio.png
Move oder löschen (git rm)

2023-12-06 23:34 UTC, michael-mezgo commented on Organize_it_activity_diagram.drawio
Move oder löschen (git rm)

2023-12-09 12:54 UTC, Nour-hash commented
> > wie verschiebe ich die alten Datein in ein ordner
> 
> Zumindest unter Unix (unter Windows sollte es auch die GitShell geben): git mv diagram.png docs/hld-pics/diagram.png
> 
> und das andere bitte unter docs/raw-documents/
> 
> Wenns leichter ist kannst du auch den Main in deinen Branch rein mergen. Dann hast du auch die directories.
> 
> @Nour-hash

hab verschoben

2023-12-10 11:46 UTC, michael-mezgo approved these changes

2023-12-10 11:46 UTC, michael-mezgo commented on docs/md-pics/Organize_it_activity_diagram-Seite-1.drawio.png
Evtl löschen? Haben es falls wir es doch brauchen eh in den alten Git Commits

2023-12-10 11:46 UTC, michael-mezgo commented on docs/md-pics/Organize_it_activity_diagram.drawio.png
Passt, wie gesagt wann SYNC DATA ausgeführt wird, ist von unserer gewählten Technologie abhängig

2023-12-10 11:46 UTC, michael-mezgo commented
@arikkof @matschl12 pls review

2023-12-10 20:37 UTC, matschl12 commented
Schaut gut aus! Nur beim ersten bin ich mir bissi unsicher ob wir da einen User/Server Bereich brauchen.

2023-12-10 21:34 UTC, michael-mezgo commented
> Schaut gut aus! Nur beim ersten bin ich mir bissi unsicher ob wir da einen User/Server Bereich brauchen.

@matschl12 du musst ein Review starten und annehmen. Sonst kann nicht gemerged werden

2023-12-10 21:35 UTC, michael-mezgo requested changes
Diagramm ok.

Bitte die alten Dateien löschen (git rm) und das neue nicht v3 nennen.
Sollten wir die alten Dateien nochmals brauchen, haben wir diese eh in den alten commits 😄

2023-12-11 08:54 UTC, Nour-hash commented
> Diagramm ok.
> 
> 
> 
> Bitte die alten Dateien löschen (git rm) und das neue nicht v3 nennen.
> 
> Sollten wir die alten Dateien nochmals brauchen, haben wir diese eh in den alten commits 😄 

Aso okay mach ich sobald ich in der fh bin

2023-12-11 08:55 UTC, Nour-hash commented
> Schaut gut aus! Nur beim ersten bin ich mir bissi unsicher ob wir da einen User/Server Bereich brauchen. 

Wir haben ja gesagt, dass der server den space für uns automatisch erstellt also hat der user nix damit zu tun sondern der server

2023-12-11 09:33 UTC, michael-mezgo requested changes
Letzter Request 🤪 

md-pics ist für die Markdown-Dateien
Im Main haben wir die `PNG`-Dateien in `/docs/hld-pics` bitte also noch verschieben :D

2023-12-11 09:33 UTC, michael-mezgo commented
@arikkof @matschl12 pls review

2023-12-11 09:37 UTC, Nour-hash commented
> Letzter Request 🤪
> 
> md-pics ist für die Markdown-Dateien Im Main haben wir die `PNG`-Dateien in `/docs/hld-pics` bitte also noch verschieben :D

passt jetzt ;)

2023-12-11 09:41 UTC, michael-mezgo approved these changes
Danke - alles perfekt

2023-12-11 14:01 UTC, matschl12 approved these changes

2023-12-11 20:54 UTC, merged