update SRS to Version 1.5
OrganizeIT-FHCW/OrganizeIT pull request #9
Opened 2023-11-26 16:06 UTC by arikkof

2023-11-26 16:07 UTC, Nour-hash submitted a review, later dismissed

2023-11-27 06:12 UTC, michael-mezgo approved these changes
Thank you!

2023-11-27 06:16 UTC, michael-mezgo requested changes
Inhaltsverzeichnis updaten

2023-11-27 11:19 UTC, michael-mezgo submitted a review, later dismissed

2023-11-28 14:28 UTC, michael-mezgo submitted a review, later dismissed

2023-11-28 14:48 UTC, michael-mezgo approved these changes

2023-11-28 14:48 UTC, matschl12 approved these changes

2023-11-28 14:48 UTC, merged